spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb
    username: root
    password: Huawei12#$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN

management:
  endpoints:
    web:
      exposure:
        include: health,info


